print("Lmao you thought this would actually install this?")
print("... Sorry, too lazy to make an installer right now, just git clone the repo.")
print("Oh, and you'll need to drop a few extra libs into the `libs` folder.")
print(" - ccryptolib: https://github.com/migeyel/ccryptolib")
print(" - logging: https://github.com/Fatboychummy-CC/Libraries/")
print(" - filesystem: https://github.com/Fatboychummy-CC/Libraries/")
print(" - errors: https://github.com/Fatboychummy-CC/Libraries/")
print(" - credential_store: https://github.com/Fatboychummy-CC/Libraries/")
print(" you may also need file_helper from the libraries repo, can't remember. I am pretty sure I moved away from it tho")